### ISSUE TITLE
Items that still need to be added:

### ISSUE THREAD

**Issue by DEV-DIBSTER** [DIBSTERYT/BrawlCDN#1]
Assets that will slowly be added within the CDN overtime:

- [x] Brawler Pin Icons (/Brawler-Pins)
- [x] Brawler Icons (/Brawler-Icons)
- [x] Brawler Portraits (/Brawler-Portraits)
- [x] Brawler Icons with Border (/Brawler-Icons-2)
- [x] Player Icons (/Player-Icons)
- [x] Club Icons (/Club-Icons)
- [x] Rank Icons (/Ranks)
- [x] Gamemode Icons (/Gamemode-Icons)
- [x] Gamemode Headers (/Gamemode-Headers)

**Comment by DEV-DIBSTER** [comment]
Rank Icons just finished [#039d794](https://github.com/DIBSTERYT/BrawlCDN/commit/039d7943da122fd84442fcf7d870ae3d07cd6b1c)

**Comment by DEV-DIBSTER** [comment]
Club Icons just finished, Player Icons just finished [69267a4](https://github.com/DIBSTERYT/BrawlCDN/commit/69267a40a400df6c113c593cdfb990ed2b3eb23a)

**Comment by DEV-DIBSTER** [comment]
Brawler Pins just finished [3de81a9](https://github.com/DIBSTERYT/BrawlCDN/commit/3de81a9f7ab7b3a6d77a88b1a3825190e66377d8)

**Comment by DEV-DIBSTER** [comment]
Brawler Icons just finished [fe7c3cd](https://github.com/DIBSTERYT/BrawlCDN/commit/fe7c3cd2c980dd20b2d60a1f01ce8dddd59a359c)

**Comment by DEV-DIBSTER** [comment]
Brawler Icons with Borders just finished [3de81a9 ](https://github.com/DIBSTERYT/BrawlCDN/commit/1570e244543f99855bdaf1533dfabc41731a30b4)

**Comment by DEV-DIBSTER** [comment]
Gamemode-Icons just finished, Gamemode-Headers just finished [597cc17](https://github.com/DIBSTERYT/BrawlCDN/commit/597cc1738ea64c8ca43b1ee42579c8850cef9a23)

**Comment by Bimi05** [comment]
Brawler Portraits has been submitted as a pr (#2)

**Comment by DEV-DIBSTER** [comment]
Brawler Portraits just merged [d37e6cf](https://github.com/DIBSTERYT/BrawlCDN/commit/d37e6cfba5de668b2176e7ab9177846f4d4aa864) thanks to @Bimi05
